# File: .github/workflows/azure-webapp-deploy.yml
name: Build and Deploy .NET Core App to Azure Web App

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

  workflow_dispatch:  # Allows manually triggering the workflow from GitHub Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v3

    # Step 2: Set up .NET Core SDK
    - name: 'Set up .NET Core'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'  # Specify your .NET SDK version

    # Step 3: Install dependencies and build the app
    - name: 'Install dependencies and build'
      run: |
        dotnet restore
        dotnet build --configuration Release

    # Step 4: Publish the app
    - name: 'Publish .NET app'
      run: dotnet publish -c Release -o ./publish

    # Step 5: Deploy to Azure Web App using Azure Web Apps Deploy action
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'  # Replace with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Set in GitHub Secrets
        package: ./publish
